Get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lhdyBNaW4gSHR3YXkiLCJpYXQiOjE3MDgwMTMwMjF9.FqpbQyciWO8D-MHQpt7ZmQWOrwGvrTvGVQSg7ZzlkTo

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyaw Min Htway"
}